// prettier-ignore
// eslint-disable
export const contributors = [
    {
        "login": "Hacksore",
        "id": 996134,
        "node_id": "MDQ6VXNlcjk5NjEzNA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/996134?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Hacksore",
        "html_url": "https://github.com/Hacksore",
        "followers_url": "https://api.github.com/users/Hacksore/followers",
        "following_url": "https://api.github.com/users/Hacksore/following{/other_user}",
        "gists_url": "https://api.github.com/users/Hacksore/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Hacksore/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Hacksore/subscriptions",
        "organizations_url": "https://api.github.com/users/Hacksore/orgs",
        "repos_url": "https://api.github.com/users/Hacksore/repos",
        "events_url": "https://api.github.com/users/Hacksore/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Hacksore/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 529
    },
    {
        "login": "maxdemaio",
        "id": 44373521,
        "node_id": "MDQ6VXNlcjQ0MzczNTIx",
        "avatar_url": "https://avatars.githubusercontent.com/u/44373521?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maxdemaio",
        "html_url": "https://github.com/maxdemaio",
        "followers_url": "https://api.github.com/users/maxdemaio/followers",
        "following_url": "https://api.github.com/users/maxdemaio/following{/other_user}",
        "gists_url": "https://api.github.com/users/maxdemaio/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/maxdemaio/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/maxdemaio/subscriptions",
        "organizations_url": "https://api.github.com/users/maxdemaio/orgs",
        "repos_url": "https://api.github.com/users/maxdemaio/repos",
        "events_url": "https://api.github.com/users/maxdemaio/events{/privacy}",
        "received_events_url": "https://api.github.com/users/maxdemaio/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 5
    },
    {
        "login": "niemal",
        "id": 9192165,
        "node_id": "MDQ6VXNlcjkxOTIxNjU=",
        "avatar_url": "https://avatars.githubusercontent.com/u/9192165?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/niemal",
        "html_url": "https://github.com/niemal",
        "followers_url": "https://api.github.com/users/niemal/followers",
        "following_url": "https://api.github.com/users/niemal/following{/other_user}",
        "gists_url": "https://api.github.com/users/niemal/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/niemal/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/niemal/subscriptions",
        "organizations_url": "https://api.github.com/users/niemal/orgs",
        "repos_url": "https://api.github.com/users/niemal/repos",
        "events_url": "https://api.github.com/users/niemal/events{/privacy}",
        "received_events_url": "https://api.github.com/users/niemal/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 3
    },
    {
        "login": "MVAodhan",
        "id": 69143973,
        "node_id": "MDQ6VXNlcjY5MTQzOTcz",
        "avatar_url": "https://avatars.githubusercontent.com/u/69143973?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MVAodhan",
        "html_url": "https://github.com/MVAodhan",
        "followers_url": "https://api.github.com/users/MVAodhan/followers",
        "following_url": "https://api.github.com/users/MVAodhan/following{/other_user}",
        "gists_url": "https://api.github.com/users/MVAodhan/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/MVAodhan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/MVAodhan/subscriptions",
        "organizations_url": "https://api.github.com/users/MVAodhan/orgs",
        "repos_url": "https://api.github.com/users/MVAodhan/repos",
        "events_url": "https://api.github.com/users/MVAodhan/events{/privacy}",
        "received_events_url": "https://api.github.com/users/MVAodhan/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 1
    },
    {
        "login": "borisnezlobin",
        "id": 146669165,
        "node_id": "U_kgDOCL3-bQ",
        "avatar_url": "https://avatars.githubusercontent.com/u/146669165?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/borisnezlobin",
        "html_url": "https://github.com/borisnezlobin",
        "followers_url": "https://api.github.com/users/borisnezlobin/followers",
        "following_url": "https://api.github.com/users/borisnezlobin/following{/other_user}",
        "gists_url": "https://api.github.com/users/borisnezlobin/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/borisnezlobin/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/borisnezlobin/subscriptions",
        "organizations_url": "https://api.github.com/users/borisnezlobin/orgs",
        "repos_url": "https://api.github.com/users/borisnezlobin/repos",
        "events_url": "https://api.github.com/users/borisnezlobin/events{/privacy}",
        "received_events_url": "https://api.github.com/users/borisnezlobin/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 1
    },
    {
        "login": "Pyr33x",
        "id": 83529331,
        "node_id": "MDQ6VXNlcjgzNTI5MzMx",
        "avatar_url": "https://avatars.githubusercontent.com/u/83529331?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Pyr33x",
        "html_url": "https://github.com/Pyr33x",
        "followers_url": "https://api.github.com/users/Pyr33x/followers",
        "following_url": "https://api.github.com/users/Pyr33x/following{/other_user}",
        "gists_url": "https://api.github.com/users/Pyr33x/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Pyr33x/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Pyr33x/subscriptions",
        "organizations_url": "https://api.github.com/users/Pyr33x/orgs",
        "repos_url": "https://api.github.com/users/Pyr33x/repos",
        "events_url": "https://api.github.com/users/Pyr33x/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Pyr33x/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 1
    },
    {
        "login": "mrnossiom",
        "id": 43814157,
        "node_id": "MDQ6VXNlcjQzODE0MTU3",
        "avatar_url": "https://avatars.githubusercontent.com/u/43814157?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrnossiom",
        "html_url": "https://github.com/mrnossiom",
        "followers_url": "https://api.github.com/users/mrnossiom/followers",
        "following_url": "https://api.github.com/users/mrnossiom/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrnossiom/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrnossiom/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrnossiom/subscriptions",
        "organizations_url": "https://api.github.com/users/mrnossiom/orgs",
        "repos_url": "https://api.github.com/users/mrnossiom/repos",
        "events_url": "https://api.github.com/users/mrnossiom/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrnossiom/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 1
    },
    {
        "login": "rishi-raj-jain",
        "id": 46300090,
        "node_id": "MDQ6VXNlcjQ2MzAwMDkw",
        "avatar_url": "https://avatars.githubusercontent.com/u/46300090?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rishi-raj-jain",
        "html_url": "https://github.com/rishi-raj-jain",
        "followers_url": "https://api.github.com/users/rishi-raj-jain/followers",
        "following_url": "https://api.github.com/users/rishi-raj-jain/following{/other_user}",
        "gists_url": "https://api.github.com/users/rishi-raj-jain/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rishi-raj-jain/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rishi-raj-jain/subscriptions",
        "organizations_url": "https://api.github.com/users/rishi-raj-jain/orgs",
        "repos_url": "https://api.github.com/users/rishi-raj-jain/repos",
        "events_url": "https://api.github.com/users/rishi-raj-jain/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rishi-raj-jain/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 1
    },
    {
        "login": "turbobot-temp",
        "id": 145653950,
        "node_id": "U_kgDOCK6Avg",
        "avatar_url": "https://avatars.githubusercontent.com/u/145653950?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/turbobot-temp",
        "html_url": "https://github.com/turbobot-temp",
        "followers_url": "https://api.github.com/users/turbobot-temp/followers",
        "following_url": "https://api.github.com/users/turbobot-temp/following{/other_user}",
        "gists_url": "https://api.github.com/users/turbobot-temp/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/turbobot-temp/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/turbobot-temp/subscriptions",
        "organizations_url": "https://api.github.com/users/turbobot-temp/orgs",
        "repos_url": "https://api.github.com/users/turbobot-temp/repos",
        "events_url": "https://api.github.com/users/turbobot-temp/events{/privacy}",
        "received_events_url": "https://api.github.com/users/turbobot-temp/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 1
    },
    {
        "login": "trobonox",
        "id": 57040351,
        "node_id": "MDQ6VXNlcjU3MDQwMzUx",
        "avatar_url": "https://avatars.githubusercontent.com/u/57040351?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/trobonox",
        "html_url": "https://github.com/trobonox",
        "followers_url": "https://api.github.com/users/trobonox/followers",
        "following_url": "https://api.github.com/users/trobonox/following{/other_user}",
        "gists_url": "https://api.github.com/users/trobonox/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/trobonox/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/trobonox/subscriptions",
        "organizations_url": "https://api.github.com/users/trobonox/orgs",
        "repos_url": "https://api.github.com/users/trobonox/repos",
        "events_url": "https://api.github.com/users/trobonox/events{/privacy}",
        "received_events_url": "https://api.github.com/users/trobonox/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 1
    },
    {
        "login": "uncenter",
        "id": 47499684,
        "node_id": "MDQ6VXNlcjQ3NDk5Njg0",
        "avatar_url": "https://avatars.githubusercontent.com/u/47499684?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/uncenter",
        "html_url": "https://github.com/uncenter",
        "followers_url": "https://api.github.com/users/uncenter/followers",
        "following_url": "https://api.github.com/users/uncenter/following{/other_user}",
        "gists_url": "https://api.github.com/users/uncenter/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/uncenter/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/uncenter/subscriptions",
        "organizations_url": "https://api.github.com/users/uncenter/orgs",
        "repos_url": "https://api.github.com/users/uncenter/repos",
        "events_url": "https://api.github.com/users/uncenter/events{/privacy}",
        "received_events_url": "https://api.github.com/users/uncenter/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 1
    }
]
