export enum RPCCommand {
  DISPATCH = "DISPATCH",
  AUTHORIZE = "AUTHORIZE",
  AUTHENTICATE = "AUTHENTICATE",
  GET_GUILD = "GET_GUILD",
  GET_GUILDS = "GET_GUILDS",
  GET_CHANNEL = "GET_CHANNEL",
  GET_CHANNELS = "GET_CHANNELS",
  GET_USER = "GET_USER",
  SUBSCRIBE = "SUBSCRIBE",
  UNSUBSCRIBE = "UNSUBSCRIBE",
  SET_USER_VOICE_SETTINGS = "SET_USER_VOICE_SETTINGS",
  SET_USER_VOICE_SETTINGS_2 = "SET_USER_VOICE_SETTINGS_2",
  SELECT_VOICE_CHANNEL = "SELECT_VOICE_CHANNEL",
  GET_SELECTED_VOICE_CHANNEL = "GET_SELECTED_VOICE_CHANNEL",
  SELECT_TEXT_CHANNEL = "SELECT_TEXT_CHANNEL",
  GET_VOICE_SETTINGS = "GET_VOICE_SETTINGS",
  SET_VOICE_SETTINGS_2 = "SET_VOICE_SETTINGS_2",
  SET_VOICE_SETTINGS = "SET_VOICE_SETTINGS",
}

/**
 *  This will ask discord for the current channel they are in
 *  and we have to get that resposne and use it to sub to other events
 * @returns Returns a payload for GET_SELECTED_VOICE_CHANNEL 
 */
export function getSelectedChannel() {
  return {
    cmd: RPCCommand.GET_SELECTED_VOICE_CHANNEL,
  };
}
