name: Publish release to WinGet
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@19e706d4c9121098010096f9c495a70a7518b30f
        with:
          identifier: OverlayedDev.Overlayed
          version: ${{ github.event.release.tag_name }}
          token: ${{ secrets.WINGET_TOKEN }}